CREATE TABLE [usr].[UserLogins]
(
	[UserId] NVARCHAR(128) NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[UserName] NVARCHAR(16) NULL,
	[EmailAddress] NVARCHAR(256) NOT NULL,
	[CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)
