CREATE TABLE [dbo].[DataTableLineage]
(
	[DataTableLineageId] INT NOT NULL PRIMARY KEY IDENTITY,
	[ParentTableId] INT NOT NULL,
	[ChildTableId] INT NOT NULL,
	[LineageStartDate] DATE NOT NULL DEFAULT '2017-01-01',
	[LineageEndDate] DATE NULL,
	[CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT SUSER_SNAME(),
	[UpdatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT SUSER_SNAME()
)
