CREATE TABLE [dbo].[Scrapes]
(
	[ScrapeId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[ScrapeScope] NVARCHAR(50) NOT NULL,
	[DynamicScrapeObject] nvarchar(50) not null,
	[DynamicScrapeObjectId] INT NOT NULL,
	[ScrapeScheduledDateTime] DATETIME2(7) NOT NULL DEFAULT GETUTCDATE(),
	[ScrapeWorkerId] UNIQUEIDENTIFIER NULL,
	[ScrapeStatusId] INT NOT NULL DEFAULT 1,
	[CreatedDate] DATETIME2(7) NOT NULL DEFAULT GETUTCDATE(),
	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT SUSER_SNAME(),
	[UpdatedDate] DATETIME2(7) NOT NULL DEFAULT GETUTCDATE(),
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT SUSER_SNAME()
)
