CREATE TABLE [dbo].[Servers]
(
	[ServerId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ServerName] NVARCHAR(100) NOT NULL, 
    [Purpose] NVARCHAR(MAX) NULL,
    [IsDevelopmentServer] BIT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [CreatedBy] NVARCHAR(50) NOT NULL DEFAULT SUSER_SNAME(), 
    [UpdatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT SUSER_SNAME()
)
