//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolboxUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataArchitecture_CanView {
            get {
                return ((bool)(this["DataArchitecture_CanView"]));
            }
            set {
                this["DataArchitecture_CanView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataArchitecture_CanRunDatabaseScrape {
            get {
                return ((bool)(this["DataArchitecture_CanRunDatabaseScrape"]));
            }
            set {
                this["DataArchitecture_CanRunDatabaseScrape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataArchitecture_CanRunSchemaScrape {
            get {
                return ((bool)(this["DataArchitecture_CanRunSchemaScrape"]));
            }
            set {
                this["DataArchitecture_CanRunSchemaScrape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataArchitecture_CanRunTableScrape {
            get {
                return ((bool)(this["DataArchitecture_CanRunTableScrape"]));
            }
            set {
                this["DataArchitecture_CanRunTableScrape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataArchitecture_CanRunFieldScrape {
            get {
                return ((bool)(this["DataArchitecture_CanRunFieldScrape"]));
            }
            set {
                this["DataArchitecture_CanRunFieldScrape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TermsAndDefinitions_CanView {
            get {
                return ((bool)(this["TermsAndDefinitions_CanView"]));
            }
            set {
                this["TermsAndDefinitions_CanView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataArchitecture_CanViewDevelopmentServers {
            get {
                return ((bool)(this["DataArchitecture_CanViewDevelopmentServers"]));
            }
            set {
                this["DataArchitecture_CanViewDevelopmentServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TermsAndDefinitions_CanAddTerm {
            get {
                return ((bool)(this["TermsAndDefinitions_CanAddTerm"]));
            }
            set {
                this["TermsAndDefinitions_CanAddTerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TermsAndDefinitions_CanEditTerm {
            get {
                return ((bool)(this["TermsAndDefinitions_CanEditTerm"]));
            }
            set {
                this["TermsAndDefinitions_CanEditTerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TermsAndDefinitions_CanRemoveTerm {
            get {
                return ((bool)(this["TermsAndDefinitions_CanRemoveTerm"]));
            }
            set {
                this["TermsAndDefinitions_CanRemoveTerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Settings_CanView {
            get {
                return ((bool)(this["Settings_CanView"]));
            }
            set {
                this["Settings_CanView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Settings_Permissions_CanView {
            get {
                return ((bool)(this["Settings_Permissions_CanView"]));
            }
            set {
                this["Settings_Permissions_CanView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Settings_Permissions_CanEditSubordinatePermissions {
            get {
                return ((bool)(this["Settings_Permissions_CanEditSubordinatePermissions"]));
            }
            set {
                this["Settings_Permissions_CanEditSubordinatePermissions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Settings_Permissions_CanEditOwnPermissions {
            get {
                return ((bool)(this["Settings_Permissions_CanEditOwnPermissions"]));
            }
            set {
                this["Settings_Permissions_CanEditOwnPermissions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserId {
            get {
                return ((string)(this["UserId"]));
            }
            set {
                this["UserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataArchitecure_CanFindDataTableLineage {
            get {
                return ((bool)(this["DataArchitecure_CanFindDataTableLineage"]));
            }
            set {
                this["DataArchitecure_CanFindDataTableLineage"] = value;
            }
        }
    }
}
